repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: statix
        name: Linter Nix (static)
        # 'nix run' descarga el paquete desde el repositorio de Nixpkgs
        # y lo ejecuta sin instalarlo globalmente.
        entry: nix run nixpkgs#statix -- check
        language: system
        files: \.nix$
        pass_filenames: false
      - id: alejandra
        name: Formatter nix
        entry: nix run nixpkgs#alejandra --
        language: system
        files: \.nix$
  - repo: https://github.com/astro/deadnix
    rev: v1.3.1
    hooks:
      - id: deadnix
        name: Nix dead code
        args:
          - --fail
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.25.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - "@commitlint/config-conventional"
