repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
  - repo: https://github.com/mrtazz/checkmake
    rev: v0.3.0
    hooks:
      - id: checkmake
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: statix
        name: Linter Nix (statix)
        entry: nix run nixpkgs#statix -- check
        language: system
        files: '\.nix$'
        stages: [pre-commit]
      - id: alejandra
        name: Formatter nix
        entry: nix run nixpkgs#alejandra --
        language: system
        files: '\.nix$'
        stages: [pre-commit]
      - id: nix-flake-check
        name: Nix Flake Check (Pre-Push)
        entry: nix flake check
        language: system
        stages: [pre-push]
        always_run: true
        pass_filenames: false
  - repo: https://github.com/astro/deadnix
    rev: v1.3.1
    hooks:
      - id: deadnix
        name: Nix dead code
        stages: [pre-commit]
        args:
          - --edit
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        stages: [pre-commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.26.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@commitlint/config-conventional"
