branches:
  - "release/v*"
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "angular"
      releaseRules:
        - subject: "*BREAKING CHANGE*"
          release: "major"
        - subject: "*NEW RELEASE*"
          release: "major"
        - body: "*BREAKING CHANGE*"
          release: "major"
        - type: "feat"
          release: "minor"
        - type: "fix"
          release: "patch"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "@semantic-release/git"
