name: Nix Build & Cachix Push
on:
  push:
    branches:
      - main
      - features/*
      - release/v*
      - pre-release/v*
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-darwin:
    name: "Darwin: ${{ matrix.host }}"
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        host: [kanagawa, outer-heaven, lsp-dummy]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SECRETS_REPO_SSH_KEY_BASE64 }}" | base64 -d > /tmp/raw_ssh_key
          echo "DECODED_KEY<<EOF" >> $GITHUB_ENV
          cat /tmp/raw_ssh_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          rm /tmp/raw_ssh_key
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ env.DECODED_KEY }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN_SECRETS }}
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: themakunga
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Eval flake for ${{matrix.host}}
        run: |
          echo "=== Runing evaluation of flake ${{matrix.host}} ==="
          nix eval .#darwinConfigurations.${{matrix.host}}.system.drvPath --accept-flake-config --show-trace
      - name: Compile Darwin
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY_CI }}
        run: |
          echo "=== Building Darwin configuration for ${{ matrix.host }} ==="
          nix build .#darwinConfigurations.${{matrix.host}}.system --accept-flake-config --print-build-logs
  build-linux-x86_64:
    name: "Linux x86: ${{ matrix.host }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [msf, motherbase, steamdeck, lsp-dummy]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SECRETS_REPO_SSH_KEY_BASE64 }}" | base64 -d > /tmp/raw_ssh_key
          echo "DECODED_KEY<<EOF" >> $GITHUB_ENV
          cat /tmp/raw_ssh_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          rm /tmp/raw_ssh_key
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ env.DECODED_KEY }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN_SECRETS }}
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: themakunga
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Evaluate Flake
        run: |
          echo "=== Running evaluation for ${{matrix.host}} ==="
          nix eval .#nixosConfigurations.${{matrix.host}}.config.system.build.toplevel.drvPath --accept-flake-config --show-trace
      - name: Compile NixOS (x86_64)
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY_CI }}
        run: |
          echo "=== Building NixOS configuration for ${{ matrix.host }} ==="
          nix build .#nixosConfigurations.${{matrix.host}}.config.system.build.toplevel --accept-flake-config --print-build-logs
  build-linux-arm64:
    name: "Linux ARM: ${{ matrix.host }}"
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        host: [aperture-science, black-mesa, valve, lsp-dummy]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SECRETS_REPO_SSH_KEY_BASE64 }}" | base64 -d > /tmp/raw_ssh_key
          echo "DECODED_KEY<<EOF" >> $GITHUB_ENV
          cat /tmp/raw_ssh_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          rm /tmp/raw_ssh_key
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ env.DECODED_KEY }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN_SECRETS }}
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux
            extra-substituters = https://nixos-hardware.cachix.org
            extra-trusted-public-keys = nixos-hardware.cachix.org-1:OqV48MwUzN0rmApeP5Dp/4hQv+8Uz7x1qPtd+6BaLgc=
      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: themakunga
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Evaluate Flake
        run: |
          export NIX_SSHOPTS="-o StrictHostKeyChecking=no"
          echo "=== Running evaluation for ${{matrix.host}} ==="
          nix eval .#nixosConfigurations.${{matrix.host}}.config.system.build.toplevel.drvPath --accept-flake-config --show-trace
      - name: Compile NixOS (arm64)
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY_CI }}
        run: |
          export NIX_SSHOPTS="-o StrictHostKeyChecking=no"
          echo "=== Building NixOS configuration for ${{ matrix.host }} ==="
          if [ "${{ matrix.host }}" == "valve" ]; then
            nix build .#nixosConfigurations.${{matrix.host}}.config.system.build.sdImage --accept-flake-config --print-build-logs
          else
            nix build .#nixosConfigurations.${{matrix.host}}.config.system.build.toplevel --accept-flake-config --print-build-logs
          fi
