name: Nix Build & Cachix Push
on:
  push:
    branches:
      - main
      - features/*
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-darwin:
    name: "Darwin: ${{ matrix.host }}"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        host: [kanagawa, outer-heaven, lsp-dummy]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SECRETS_REPO_SSH_KEY_BASE64 }}" | base64 -d > /tmp/raw_ssh_key
          echo "DECODED_KEY<<EOF" >> $GITHUB_ENV
          cat /tmp/raw_ssh_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          rm /tmp/raw_ssh_key
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ env.DECODED_KEY }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN_SECRETS }}
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: themakunga
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Eval flake for ${{matrix.host}}
        run: |
          echo "=== Runing evaluation of flake ${{matrix.host}} ==="
          nix eval .#darwinConfigurations.${{matrix.host}}.system.drvPath --accept-flake-config --show-trace
      - name: Compile Darwin
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY_CI }}
        run: |
          echo "=== Building Darwin configuration for ${{ matrix.host }} ==="
          nix build .#darwinConfigurations.${{matrix.host}}.system --accept-flake-config --print-build-logs
  build-linux-x86_64:
    name: "Linux x86: ${{ matrix.host }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [msf, motherbase, steamdeck, lsp-dummy]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SECRETS_REPO_SSH_KEY_BASE64 }}" | base64 -d > /tmp/raw_ssh_key
          echo "DECODED_KEY<<EOF" >> $GITHUB_ENV
          cat /tmp/raw_ssh_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          rm /tmp/raw_ssh_key
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ env.DECODED_KEY }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN_SECRETS }}
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: themakunga
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Evaluate Flake
        run: |
          echo "=== Running evaluation for ${{matrix.host}} ==="
          nix eval .#nixosConfigurations.${{matrix.host}}.config.system.build.toplevel.drvPath --accept-flake-config --show-trace
      - name: Compile NixOS (x86_64)
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY_CI }}
        run: |
          echo "=== Building NixOS configuration for ${{ matrix.host }} ==="
          nix build .#nixosConfigurations.${{matrix.host}}.config.system.build.toplevel --accept-flake-config --print-build-logs
  build-linux-arm64:
    name: "Linux ARM: ${{ matrix.host }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [aperture-science, black-mesa, valve, lsp-dummy]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Configure QEMU for ARM64 Emulation
        uses: docker/setup-qemu-action@v4
        with:
          platforms: arm64
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SECRETS_REPO_SSH_KEY_BASE64 }}" | base64 -d > /tmp/raw_ssh_key
          echo "DECODED_KEY<<EOF" >> $GITHUB_ENV
          cat /tmp/raw_ssh_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          rm /tmp/raw_ssh_key
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ env.DECODED_KEY }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN_SECRETS }}
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux
      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: themakunga
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Evaluate Flake
        run: |
          echo "=== Running evaluation for ${{matrix.host}} ==="
          nix eval .#nixosConfigurations.${{matrix.host}}.config.system.build.toplevel.drvPath --accept-flake-config --show-trace
      - name: Compile NixOS (arm64)
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY_CI }}
        run: |
          echo "=== Building NixOS configuration for ${{ matrix.host }} ==="
          nix build .#nixosConfigurations.${{matrix.host}}.config.system.build.toplevel --accept-flake-config --print-build-logs
  create-release-branch:
    name: "Create Release Branch"
    needs: [build-darwin, build-linux-x86_64, build-linux-arm64]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Create and push release branch
        run: |
          # Generamos el timestamp formato YYYYMMDDHHMMSS
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          BRANCH_NAME="release/v$TIMESTAMP"

          echo "=== Creando la rama de release: $BRANCH_NAME ==="
          git checkout -b "$BRANCH_NAME"

          # Empujamos la rama nueva al repositorio
          git push origin "$BRANCH_NAME"
  create-prerelease-branch:
    name: "Create Pre-Release Branch (ARM64 OK)"
    # Aquí está el truco: SOLO espera a que el job de ARM64 termine con éxito
    needs: [build-linux-arm64]
    runs-on: ubuntu-latest
    # Se ejecuta solo si estamos en la rama main
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Necesario para poder crear ramas y hacer push
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Create and push pre-release branch
        run: |
          # Generamos el timestamp formato YYYYMMDDHHMMSS
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          BRANCH_NAME="pre-release/v$TIMESTAMP"

          echo "=== Creando la rama de pre-release: $BRANCH_NAME ==="
          git checkout -b "$BRANCH_NAME"

          # Empujamos la rama nueva al repositorio
          git push origin "$BRANCH_NAME"
