name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  tests:
    name: Run Nix Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup SSH for private inputs
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SECRETS_REPO_SSH_KEY }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN_SECRETS }}
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: themakunga
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Run Nix Flake Checks
        run: nix flake check -L --accept-flake-config
  build-image:
    name: Build RPi Images
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - host: glados
          - host: cornholio
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU (ARM)
        uses: docker/setup-qemu-action@v3
        with:
          platform: arm64
      - name: Setup SSH for private inputs
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SECRETS_REPO_SSH_KEY }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN_SECRETS }}
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: themakunga
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Build SD Image
        run: |
          nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.sdImage -L --accept-flake-config
          mkdir -p output
          cp -L result/sd-image/*.img.zst output/${{ matrix.host }}.img.zst
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.host }}-image
          path: output/${{ matrix.host}}.img.zst
  release:
    name: Semantic Release
    needs: build-image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          featch-depth: 0
      - name: Download all Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets
          merge-multiple: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
