name: Semantic Release
on:
  workflow_run:
    workflows:
      - "Nix Build & Cachix Push"
    types:
      - completed
    branches:
      - release/v*
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  build:
    name: Build SD Image ${{matrix.target}}
    runs-on: ubuntu-24.04-arm
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        target: [aperture-science, black-mesa, valve]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SECRETS_REPO_SSH_KEY_BASE64 }}" | base64 -d > /tmp/raw_ssh_key
          echo "DECODED_KEY<<EOF" >> $GITHUB_ENV
          cat /tmp/raw_ssh_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          rm /tmp/raw_ssh_key
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ env.DECODED_KEY }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN_SECRETS }}
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux
            extra-substituters = https://nixos-hardware.cachix.org
            extra-trusted-public-keys = nixos-hardware.cachix.org-1:OqV48MwUzN0rmApeP5Dp/4hQv+8Uz7x1qPtd+6BaLgc=
      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: themakunga
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Build SD Image
        run: |
          mkdir -p output
          echo "=> Building ${{ matrix.target }}..."
          make build-${{ matrix.target }}
          for file in result/sd-image/*.zst; do
            filename=$(basename "$file")
            cp -L "$file" "output/${{ matrix.target }}-$filename"
          done
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: image-${{ matrix.target }}
          path: output/*.zst
          retention-days: 1
  release:
    name: Tags, Publish and Cleanup
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Download Built Images
        uses: actions/download-artifact@v8
        with:
          path: output
          pattern: image-*
          merge-multiple: true
      - name: Run Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Upload Image to GitHub Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: output/*.zst
          file_glob: true
          tag: ${{ steps.semantic.outputs.new_release_git_tag }}
          overwrite: true
      - name: Direct Merge to Main and Cleanup Branches
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          BRANCH_NAME="${{ github.event.workflow_run.head_branch }}"
          PRE_REL_BRANCH="${BRANCH_NAME/release\//pre-release\/}"

          echo "=> S
