name: Security Audit (Secrets & Keys)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"
jobs:
  scan-security:
    name: Scan for exposed secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run gitleak
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{secrets.GH_PAT_SECRETS}}
