name: Update Secrets and Trigger Patch Release
on:
  repository_dispatch:
    types: [update-secrets]
permissions:
  contents: write
  pull-requests: write
jobs:
  patch-release:
    name: Bump Patch and Update Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Setup SSH Agent for Private Repo
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SECRETS_REPO_SSH_KEY }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.RELEASE_TOKEN }}
      - name: Bump Version
        id: version
        uses: anothrNick/github-tag-action@v1
        env:
          TAG_PREFIX: v
          PRERELEASE: true
          DEFAULT_BUMP: patch
          DRY_RUN: true
      - name: Update Secrets Input
        run: |
          NEW_VERSION=${{ steps.version.outputs.new_tag }}
          git checkout -b release/$NEW_VERSION
          nix flake lock --update-input secrets --accept-flake-config
      - name: Commit and Push Release Branch
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          NEW_VERSION=${{ steps.version.outputs.new_tag }}

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add flake.lock

          git commit -m "fix(secrets): bump secrets reference for $NEW_VERSION"

          git push origin release/$NEW_VERSION
